### ISSUE TITLE
il manque l'import fs dans ton fichier main.js

### ISSUE THREAD

**Issue by nicolashedoire** [DoFabien/cadastre-pg#2]
Voici mon code

`// https://www.npmjs.com/package/cadastre-pg
const cadastrePg = require('cadastre-pg');

let options = {
  schema: 'public',
  year: 2019,
  srid: 2154,
  threads: 8,
  codeDep: null,
  logLevel: 3,
  dropSchema: false,
  dropTable: false,
};

let pgConfig = {
  user: 'postgres',
  host: 'localhost',
  database: 'test',
  password: 'postgres',
  port: 5432,
};

cadastrePg('cadastre-files/dep01/01001', 'full', pgConfig, options)
  .then((t) => {
    console.log(t);
    console.log('import terminé');
  })
  .catch((error) => {
    console.log(error);
  });
`

voici l'erreur

fileName cadastre-files/dep01/01001/edigeo-01001000ZL01.tar.bz2
ReferenceError: fs is not defined
    at process.<anonymous> (/Users/nicolashedoire/Documents/brik-backend/node_modules/cadastre-pg/main.js:129:44)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
undefined

il manque l'import fs dans ton fichier main.js

**Comment by DoFabien** [comment]
Oups, oui en effet...
Je vais corriger ça, merci. 

Mais le mieux est d'utiliser la valeur "fromFile" dans l'option 'codeDep' (codeDep: 'fromFile'),. Le script va déterminer le code du département a partir du nom du fichier, ça marche bien avec les EDIGEO en opendata.

Avec _codeDep: null_, le script devrait déterminer de façon géographique le département, a partir d'un geojson de 2019... Enfin quand ce sera fixé
